-- 1. Таблица товаров (которая у нас была)
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  name TEXT,
  category TEXT,
  price NUMERIC,
  image TEXT,
  hidden_partner_name TEXT,
  hidden_partner_address TEXT
);

-- 2. Таблица заказов (сразу с новым полем status!)
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  customer_name TEXT,
  phone TEXT,
  address TEXT,
  payment_method TEXT,
  total_price NUMERIC,
  items JSONB,
  status TEXT DEFAULT 'Новый'
);

-- 3. Таблица отзывов
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  order_id BIGINT REFERENCES orders(id),
  customer_name TEXT,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  comment TEXT
);